// src/components/PostMeta/PostMeta.jsx
import React,{Component} from 'react';
import PropTypes from 'prop-types';
import Link from "gatsby-link"
import {isEmpty} from 'lodash'

import './PostMeta.scss';

class PostMeta extends Component {
	render(){
		let {datetime, tags} = this.props;
		return (			
			<div className="post-meta">
				{datetime !== '' && 
				    <div className="post-date">        
				        <time className="dateline" dateTime={datetime} itemProp="dateModified" content={datetime}>{datetime}</time>
				    </div>	
			    }
			    {!isEmpty(tags) &&
				    <div className="post-category">
					    {
					    	tags.map( tag => {
					    		return <Link activeClassName="active" key={tag} to={`/tags/${tag}`}>{tag}</Link>   
					    	})
					    }
				    </div>
			    }	    			    
			</div>	
		);
	}
}
PostMeta.propTypes = {
	datetime: PropTypes.string,
	tags: PropTypes.any
}
PostMeta.defaultProps = {
	datetime: '',
	tags: []
}
export default PostMeta;

// src/components/PostMeta.vue
<template>
  <div class="post-meta">
    Đăng ngày
    <time
      :dateTime="post.date"
      itemprop="dateModified"
      :content="post.date"
    >{{ post.date }}</time>.
    <template v-if="post.timeToRead">
      Mất khoảng
      <strong>{{ post.timeToRead }} phút</strong> để đọc.
    </template>
  </div>
</template>

<script>
export default {
  props: ["post"],
};
</script>

<style lang="scss">
.post-meta {
  font-size: 0.8em;
  opacity: 0.8;
}
</style>
